[package]
name = "crabstore-store"
version = "0.0.1"
repository.workspace = true
description = "Server for storing large binary object"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
